### ISSUE TITLE
PressFragment example invalid argument to .addMotion

### ISSUE THREAD

**Issue by ersin-ertan** [tumblr/Backboard#15] opened 2016-05-27 08:09 UTC
https://github.com/tumblr/Backboard/blob/42f153ee5c96e49da25732fc6120bb22e087daff/backboard-example/src/main/java/com/tumblr/backboard/example/PressFragment.java#L27

Actor.Builder's .addMotion method no longer takes a ToggleImitator, and even if it did, the ToggleImitator no longer takes a null spring for it's first argument.

**Comment by ericleong** [comment] 2016-08-10 20:02
Duplicate of #14

**Closed as completed by ericleong** 2016-08-10 20:02 UTC
Labels: bug
